### ISSUE TITLE
support texts whose "visual widths" are not equal to "lengths"

### ISSUE THREAD

**Issue by skaji** [neilb/Text-Table-Tiny#12]
It is nice this module supports texts whose visual widths are not equal to `length $text`.

Currently:

```perl
use strict;
use warnings;
use utf8;
use Text::Table::Tiny 'generate_table';

binmode \*STDOUT, ":utf8";

my $rows = [
    ["example"],
    ["😄"],
    ["こんにちは"],
];

print generate_table(rows => $rows), "\n";
print generate_table(rows => $rows, style => 'boxrule'), "\n";
```

<img width="158" alt="Screen Shot 2020-09-10 at 1 30 56" src="https://user-images.githubusercontent.com/1589550/92626741-4b2f5280-f305-11ea-851f-874f4c2f12b7.png">

**Comment by neilb** [comment]
This "Tiny" module is going to end up not quite so tiny, eh Kaji-san.

I'll do some research to find the best way to determine the "tty width" of a string, and see if I can fix your example!

**Comment by skaji** [comment]
Now Text-Table-Tiny supports texts whose "visual widths" are not equal to "lengths".

@neilb Thanks!
