### ISSUE TITLE
Add an option for ANSI row/column separators for added fanciness

### ISSUE THREAD

**Issue by scottchiefbaker** [neilb/Text-Table-Tiny#8]
ASCII tables are great, but feel very 1990s. 

It would be cool if there was an `ansi_output => 1` option for `generate_table()` to generate nicer looking tables.

**Comment by neilb** [comment]
The version currently in developer release adds a `style` parameter:

    style => 'boxrule'

Gives what I think you were after?

The existing look is style `'classic'`, and you can also use `'norule'`, which generates a columnar output with no rules.

**Comment by scottchiefbaker** [comment]
Looks good to me! I get:

    Wide character in print at /tmp/x.pl line 21.

When I use `boxrule` though. I assume I need to set STDOUT to be UTF8? Maybe that's something the module could do if boxrule is enabled?

**Comment by neilb** [comment]
Given the module returns a string, rather than prints to STDOUT, I don't think it would be right for it to `binmode()` on STDOUT. I'll add it to the documentation though.

I'll add handling of escape codes in the next dev release as well.

**Comment by scottchiefbaker** [comment]
Sounds good! I like it.

**Comment by neilb** [comment]
Now released in version 1.00.
